spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/biblio
    username: postgres
    password: 123
  flyway:
    baseline-on-migrate: true
